# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Christine Dowling
description: "Hi I'm Christine, a data science and machine learning professional. This page features a selection of projects I've worked on showcasing different skills and the range of business problems data science can be used for. In each project I describe my methodology and results, along with any other interesting insights I gained. If you'd like to view the code supporting these projects, please visit my Github at the link below. If you'd like to connect, you can donwload my resume or connect via LinkedIn"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB, Canada"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/christine-dowling-a92844116" # Add your linkedln handle
github: "https://github.com/cadowling/project-portfolio"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

